# Site
repository: p15anez/cv-1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Emmanouil Anezinis
title: Undergraduate student
email: p15anez@ionio.gr
website: p15anez.github.io/cv-1

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  p15anez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: A
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Emmmanouil Anezinis and i am an undergraduate student at Ionian University's Department of Informatics.
  The fields in which have spent the most time on are:
  - Health Data Analytics
  - Bioinformatics
  - Decision Support Systems
  - Statistics
  

content:
  - title: Education
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Sc. Informatics
        link: di.ionio.gr
        # link_text: boringcompany.com
        sub_title: Ionian University, Corfu GR
        caption: October 2015 - present
        description: |
                Specilization in Information Systems.

        Main courses follow: 
        - Health Data Analytics
        - Decision Support Systems
        - Bioinformatics

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bartender
        caption: 2015 - 2017
        sub_title: Royal Boutique Hotel, Corfu GR         
        description: | # this will include new lines to allow paragraphs
          During my working experience in this hotel i had great experiences regarding serving and communicating with clients, which in my opinion is considered as a pretty valuable lesson. I had impecable cooperation with my co-workers, a fact that made our working- time much more productive and easy-going.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Without considering Informatics, i got multiple other interests which are listed below:
      - Tech Savvy
      - Gaming
      - Spear-fishing
      - Coffee brewing
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
